### ISSUE TITLE
Опечатка?

### ISSUE THREAD

**Issue by istamendil** [whooehoo/ymaps-touch-scroll#4]
https://github.com/whooehoo/ymaps-touch-scroll/blob/313def1a43de1f35acab8efca349c6b3a340e796/dist/ymaps-touch-scroll.js#L138

В определении типа устройства написано a**nr**oid. Должно быть A**ndr**oid?

**Comment by whooehoo** [comment]
Да, спасибо!

https://github.com/whooehoo/ymaps-touch-scroll/commit/7c52fde1b9b6a70cf76c999d9951f44abfaa15d6
