### ISSUE TITLE
Андроид

### ISSUE THREAD

**Issue by ymapstester** [whooehoo/ymaps-touch-scroll#5]
на андройде при прокрутке покарте показывает подсказку, но сайт не скроллится

**Comment by whooehoo** [comment]
можно ссылку на пример, название девайса и браузера?

**Comment by whooehoo** [comment]
> на андройде при прокрутке покарте показывает подсказку, но сайт не скроллится

можно ссылку на пример, название девайса и браузера?

**Comment by ymapstester** [comment]
redmi 4x, google chrome, yandex chrome, примера к сожалению нет

**Comment by ru-dmitry** [comment]
Собственно, эта проблема появилась на всех сайтах, где карта в div'е независимо от мобильного устройства. Для примера: https://arealtypro.citrus-demo.ru

**Comment by ru-dmitry** [comment]
Уточню, что проблема появилась несколько месяцев назад, и заключается в том, что сайт перестал прокручиваться одним пальцем. То есть при тапе одним пальцем на подсказке не прокручивается ни карта, ни сайт.

**Comment by whooehoo** [comment]
@ru-dmitry спасибо за пример.

Посмотрел, проблема в самих картах.
На андроиде (на iOS работает) при выключенном перемещении карты перестает работать скролл страницы.
`behaviors.disable('drag')`

Буду пробовать другой подход к показу блока.

**Comment by ru-dmitry** [comment]
Если это правильнее исправить со стороны кодеров сайтов, может дать им рекомендации, что нужно сделать? Пусть сами фиксят.

**Comment by whooehoo** [comment]
@ru-dmitry @ymapstester 
Получилось поправить, обновите библиотеку
